name: Mirror WordPress Plugin

on:
  schedule:
    - cron: '0 0 3,15 * *'  # Runs twice a month at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  mirror:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Install Subversion
        run: sudo apt-get install subversion

      - name: Mirror from WordPress.org
        run: |
          LATEST_TAG=$(svn ls https://plugins.svn.wordpress.org/food-store/tags/ | sort -V | tail -n 1 | tr -d '/')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest tag: $LATEST_TAG"

          if git rev-parse "v$LATEST_TAG" >/dev/null 2>&1; then
            echo "Tag v$LATEST_TAG already exists. Skipping mirror."
            exit 0
          fi

          svn export https://plugins.svn.wordpress.org/food-store/tags/$LATEST_TAG svn_temp
          cp -R svn_temp/* .
          rm -rf svn_temp
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Mirror WordPress plugin version ${{ env.LATEST_TAG }}
          tagging_message: 'v${{ env.LATEST_TAG }}'