name: Mirror WordPress Plugin

on:
  schedule:
    - cron: '0 0 3,15 * *'  # Runs monthly at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Subversion
      run: sudo apt-get install subversion

    - name: Mirror from WordPress.org
      run: |
        # Get the latest tag
        LATEST_TAG=$(svn ls https://plugins.svn.wordpress.org/food-store/tags/ | sort -V | tail -n 1 | tr -d '/')
        echo "Latest tag: $LATEST_TAG"

        # Checkout the latest tag
        svn export https://plugins.svn.wordpress.org/food-store/tags/$LATEST_TAG svn_temp

        # Remove everything except .git and .github
        find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' -exec rm -rf {} +

        # Copy new files
        cp -R svn_temp/. .
        rm -rf svn_temp
    
    - name: Commit and push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Mirror WordPress plugin version $LATEST_TAG" && git push)

    - name: Create new tag
      run: |
        LATEST_TAG=$(svn ls https://plugins.svn.wordpress.org/food-store/tags/ | sort -V | tail -n 1 | tr -d '/')
        git tag -a $LATEST_TAG -m "Version $LATEST_TAG"
        git push origin $LATEST_TAG