name: Mirror WordPress Plugin

on:
  schedule:
    - cron: '0 0 3,15 * *'  # Runs monthly at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Subversion
      run: sudo apt-get install subversion

    - name: Mirror from WordPress.org
      run: |
        svn checkout https://plugins.svn.wordpress.org/food-store/ svn_temp
        rsync -avz --delete svn_temp/ ./ --exclude='.git' --exclude='.github'
        rm -rf svn_temp

    - name: Commit and push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Mirror WordPress plugin" && git push)